In [1]:
import pandas as pd
from pycaret.classification import *

In [2]:
training = pd.read_pickle('../data/te_sg_df_training_unshared.pickle')
testing = pd.read_pickle('../data/te_sg_df_testing_unshared.pickle')

In [3]:
cols = [col for col in training.columns.to_list() if col not in ['tweet', 'category']]

In [4]:
training = training[cols]
testing = testing[cols]

In [5]:
exp = setup(data=training, target='label', train_size=0.8, fold=5)

In [6]:
compare_models()

In [7]:
model = create_model('lightgbm')

In [8]:
model = tune_model(model, optimize = 'F1')

In [9]:
evaluate_model(model)

interactive(children=(ToggleButtons(description='Plot Type:', icons=('',), options=(('Hyperparameters', 'param…

In [10]:
from sklearn.metrics import classification_report

### Testing Performance

In [11]:
y_score = predict_model(model, data=testing).Score
y_pred = predict_model(model, data=testing)['Label']
y_true = testing.label

In [12]:
print(classification_report(y_true, y_pred, labels=None, target_names=None))

              precision    recall  f1-score   support

           0       0.65      0.88      0.75       280
           1       0.81      0.53      0.64       277

    accuracy                           0.70       557
   macro avg       0.73      0.70      0.69       557
weighted avg       0.73      0.70      0.69       557